version: '3'
services:
  backend:
    build:
      context: ./services/kirbymain
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always